language: rust
env:
  global:
    - secure: EqB108q0eF7NyYlj4iI4MdPI5EhKC/foJjE9hXCPCHvOaeJMkuG2UcQCGwUb7Yb1XL64ORhjL7uYpjw8t0U82ADvyJ0fgUQp/SO1582bKqXXaEpNAK5j0+AcSb4rAPG77uBJCxedIPPLvvVuEV9guIoPRk+gL07uxUWr3fF/1C0=
script:
  - cargo build
  - cargo test
  - cargo doc
after_script:
  - cp -r target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
