language: rust
os:
    - linux
    - osx

install:
    - sudo add-apt-repository ppa:team-xbmc/ppa -y
    - sudo apt-get update -q
    - sudo apt-get install libsdl2-dev
script:
    - cargo build --verbose
    - cargo build --verbose --features sdl
    - cargo test --verbose
    - cargo test --verbose --features sdl
after_success: |
    - rm -rf target/doc
    - cargo doc
    - curl -X POST -H "Github:TomBebbington/reminisce" http://www.rustdox.com
