[package]
name = "reminisce"
version = "0.0.2"
authors = ["Tom Bebbington <tophattedcoder@gmail.com>"]
description = "A joystick detection and event-handling library"
keywords = [ "joystick", "gamepad", "input" ]
license = "MIT"

[lib]
name = "reminisce"

[[bin]]
name = "main"
path = "src/main.rs"