[package]
name = "reminisce"
version = "0.0.7"
authors = ["Tom Bebbington <tophattedcoder@gmail.com>"]
description = "A joystick detection and event-handling library"
documentation = "http://www.rustdox.com/TomBebbington/reminisce/reminisce/"
keywords = [ "joystick", "gamepad", "input" ]
license = "MIT"

[lib]
name = "reminisce"

[features]
sdl = [ "sdl2" ]
default = []


[dependencies.sdl2]
version = "*"
optional = true
