[package]
name = "reminisce"
version = "0.0.6"
authors = ["Tom Bebbington <tophattedcoder@gmail.com>"]
description = "A joystick detection and event-handling library"
documentation = "http://tombebbington.github.io/reminisce/"
keywords = [ "joystick", "gamepad", "input" ]
license = "MIT"

[lib]
name = "reminisce"

[[bin]]
name = "main"
path = "src/main.rs"
