baseurl = "http://tombebbington.github.io/reminisce/"
languageCode = "en-gb"
title = "Reminisce"
theme = "pixyll"
buildDrafts = true
canonifyurls = true
[params]
  description = "A lightweight Gamepad input library in Rust"
  author = "Tom Bebbington"
